# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190317_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tag',
            field=models.CharField(default='羊驼世界', max_length=10, verbose_name='机构标签'),
        ),
    ]
