# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='tag',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='羊驼世界', max_length=10, verbose_name='机构标签'),
        ),
    ]
