# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-21 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190321_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_num',
            new_name='click_nums',
        ),
    ]
