# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-27 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190325_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='addres',
            new_name='address',
        ),
    ]
