# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-27 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190327_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickname',
            new_name='nick_name',
        ),
    ]
